#  Named of the workflow.
name: nd064-udaconnect-app  - Package with Docker
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on:
  push:
    # branches:
    #   - "main"
    # tags:
    #   - 'v*'
jobs:
  ## The name of the job
  deployment:
    ## Configure the operating system the workflow should run on.
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # - 
      #   name: Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: gampie/techtrends
      #     tags: |
      #       type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build / Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend/
          file: ./modules/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nd064-udaconnect-app:latest
          # By default we also get the "latest" tag
          # tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
